import { Roboto } from "next/font/google"; 
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"], 
  style: ["normal", "italic"], 
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
